/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package httpcliente.gui;

import httpcliente.model.Departamento;
import httpcliente.service.DepartamentoHttp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author jahaziel
 */
public class DepartamentoGUI extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private Departamento departamento;
    private final DepartamentoHttp departamentoRequest;
    private JSONObject json;
    private DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form DepartamentoGUI
     */
    public DepartamentoGUI() {
        initComponents();
        departamentoRequest = new DepartamentoHttp();
    }

    private static DepartamentoGUI deptogui = null;

    public static DepartamentoGUI getInstance() {
        if (deptogui == null) {
            deptogui = new DepartamentoGUI();
        }
        return deptogui;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDepartamento = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtIdB = new javax.swing.JTextField();
        btoBuscar = new javax.swing.JButton();
        btoEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btoGuardar = new javax.swing.JButton();
        btoActualizar = new javax.swing.JButton();
        btoListar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btoLimpiar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEPARTAMENTO - CRUD");

        tblDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDepartamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDepartamento);
        if (tblDepartamento.getColumnModel().getColumnCount() > 0) {
            tblDepartamento.getColumnModel().getColumn(0).setMinWidth(100);
            tblDepartamento.getColumnModel().getColumn(0).setMaxWidth(100);
            tblDepartamento.getColumnModel().getColumn(1).setMinWidth(300);
            tblDepartamento.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar y Elimar por:"));

        jLabel6.setText("ID:");

        btoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/httpcliente/icon/lupa.png"))); // NOI18N
        btoBuscar.setText("Buscar");
        btoBuscar.setToolTipText("Buscar");
        btoBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoBuscarActionPerformed(evt);
            }
        });

        btoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/httpcliente/icon/eliminar.png"))); // NOI18N
        btoEliminar.setText("Eliminar");
        btoEliminar.setToolTipText("Eliminar");
        btoEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdB))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btoBuscar)
                .addGap(22, 22, 22)
                .addComponent(btoEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(4, 2, 2))); // NOI18N

        jLabel2.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripcion:");

        btoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/httpcliente/icon/guardar.png"))); // NOI18N
        btoGuardar.setText("Guardar");
        btoGuardar.setToolTipText("Guardar");
        btoGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btoGuardar.setFocusable(false);
        btoGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoGuardarActionPerformed(evt);
            }
        });

        btoActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/httpcliente/icon/actualizar.png"))); // NOI18N
        btoActualizar.setText("Actualizar");
        btoActualizar.setToolTipText("Actualizar");
        btoActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btoActualizar.setFocusable(false);
        btoActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoActualizarActionPerformed(evt);
            }
        });

        btoListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/httpcliente/icon/listar.png"))); // NOI18N
        btoListar.setText("Listar");
        btoListar.setToolTipText("Listar");
        btoListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btoListar.setFocusable(false);
        btoListar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoListar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoListarActionPerformed(evt);
            }
        });

        jLabel7.setText("ID:");

        txtId.setEnabled(false);

        btoLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/httpcliente/icon/eraser.png"))); // NOI18N
        btoLimpiar.setText("Limpiar");
        btoLimpiar.setToolTipText("Listar");
        btoLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btoLimpiar.setFocusable(false);
        btoLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)
                        .addComponent(jLabel2))
                    .addComponent(btoGuardar))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btoActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btoLimpiar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtNombre)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btoLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDepartamentoMouseClicked
        int selecion = tblDepartamento.rowAtPoint(evt.getPoint());
        txtId.setText(tblDepartamento.getValueAt(selecion, 0) + "");
        txtNombre.setText(tblDepartamento.getValueAt(selecion, 1) + "");
        txtDescripcion.setText(tblDepartamento.getValueAt(selecion, 2) + "");
    }//GEN-LAST:event_tblDepartamentoMouseClicked

    private void btoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoBuscarActionPerformed
        try {
            json = new JSONObject(departamentoRequest.getDeptoById(txtIdB.getText()));
            modelo = ((DefaultTableModel) tblDepartamento.getModel());
            limpiarTabla();
            limpiar();
            modelo.addRow(new Object[]{
                json.get("id"),
                json.get("nombre"),
                json.get("descripcion"),
            });
            limpiar();
        } catch (Exception ex) {
            Logger.getLogger(DepartamentoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btoBuscarActionPerformed

    private void btoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoEliminarActionPerformed
        try {
            departamentoRequest.deleteDepto(txtIdB.getText());
            limpiar();
        } catch (Exception ex) {
            Logger.getLogger(DepartamentoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btoEliminarActionPerformed

    private void btoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoGuardarActionPerformed
        try {
            if (txtNombre.getText().isEmpty() || txtDescripcion.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Aviso! Campos del formulario vacios");
            } else {
                departamento = new Departamento();
                departamento.setNombre(txtNombre.getText());
                departamento.setDescripcion(txtDescripcion.getText());

                json = new JSONObject(departamento);
                departamentoRequest.addDepto(json.toString());
                JOptionPane.showMessageDialog(null, "Departamento Registrado");
                limpiar();
            }
        } catch (Exception ex) {
            Logger.getLogger(DepartamentoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btoGuardarActionPerformed

    private void btoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoActualizarActionPerformed
        try {
            departamento = new Departamento();
            departamento.setId(Long.valueOf(txtId.getText()));
            departamento.setNombre(txtNombre.getText());
            departamento.setDescripcion(txtDescripcion.getText());

            json = new JSONObject(departamento);
            departamentoRequest.updateDepto(json.toString());
            JOptionPane.showMessageDialog(null, "Departamento Actualizado");
            limpiar();
        } catch (Exception ex) {
            Logger.getLogger(DepartamentoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btoActualizarActionPerformed

    private void btoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoListarActionPerformed
        JSONArray jsonArray;
        try {
            jsonArray = new JSONArray(departamentoRequest.getAllDeptos());
            modelo = ((DefaultTableModel) tblDepartamento.getModel());
            limpiarTabla();
            Object[] ob = new Object[3];
            for (int i = 0; i < jsonArray.length(); i++) {
                ob[0] = jsonArray.getJSONObject(i).getLong("id");
                ob[1] = jsonArray.getJSONObject(i).getString("nombre");
                ob[2] = jsonArray.getJSONObject(i).getString("descripcion");
                modelo.addRow(ob);
            }
        } catch (Exception ex) {
            Logger.getLogger(DepartamentoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btoListarActionPerformed

    private void btoLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoLimpiarActionPerformed
        limpiarTabla();
        limpiar();
    }//GEN-LAST:event_btoLimpiarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    public void limpiar() {
        txtId.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtIdB.setText("");
    }

    public void limpiarTabla() {
        int numDatos = modelo.getRowCount();
        for (int i = 0; i < numDatos; i++) {
            modelo.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoActualizar;
    private javax.swing.JButton btoBuscar;
    private javax.swing.JButton btoEliminar;
    private javax.swing.JButton btoGuardar;
    private javax.swing.JButton btoLimpiar;
    private javax.swing.JButton btoListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDepartamento;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdB;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
